services:
  mysqldb:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: bookscout
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -pqwerty" ]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 10s

  backend:
    image: bookscout-backend
    container_name: backend
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      MYSQL_URL: //mysqldb:3306/bookscout
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: qwerty
      GOOGLE_BOOKS_API_KEY: ${GOOGLE_BOOKS_API_KEY}
    ports:
      - "8080:8080"